### ISSUE TITLE
Failing npm install

### ISSUE THREAD

**Issue by eliduke** [electron-userland/electron-spellchecker#157]
I'm not having any luck with `npm install`. First off, here are my details:

```
Node v7.9.0
NPM v5.6.0
Electron v1.8.8
```

Here's the error output from `npm i electron-spellchecker`:

```
1 error generated.
make: *** [Release/obj.target/spellchecker/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/eliduke/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/eliduke/.nvm/versions/node/v7.9.0/bin/node" "/Users/eliduke/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/eliduke/Projects/Code/electron-project/node_modules/@felixrieseberg/spellchecker
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @felixrieseberg/spellchecker@4.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @felixrieseberg/spellchecker@4.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eliduke/.npm/_logs/2019-07-24T21_57_16_048Z-debug.log
```

I checked those debug logs and I'm seeing this:

```
624 verbose stack Error: @felixrieseberg/spellchecker@4.0.10 install: `node-gyp rebuild`
624 verbose stack Exit status 1
624 verbose stack     at EventEmitter.<anonymous> (/Users/eliduke/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
624 verbose stack     at emitTwo (events.js:106:13)
624 verbose stack     at EventEmitter.emit (events.js:194:7)
624 verbose stack     at ChildProcess.<anonymous> (/Users/eliduke/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
624 verbose stack     at emitTwo (events.js:106:13)
624 verbose stack     at ChildProcess.emit (events.js:194:7)
624 verbose stack     at maybeClose (internal/child_process.js:899:16)
624 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
625 verbose pkgid @felixrieseberg/spellchecker@4.0.10
626 verbose cwd /Users/eliduke/Projects/Code/electron-project/
627 verbose Darwin 18.6.0
628 verbose argv "/Users/eliduke/.nvm/versions/node/v7.9.0/bin/node" "/Users/eliduke/.nvm/versions/node/v7.9.0/bin/npm" "install" "electron-spellchecker"
629 verbose node v7.9.0
630 verbose npm  v5.6.0
631 error code ELIFECYCLE
632 error errno 1
633 error @felixrieseberg/spellchecker@4.0.10 install: `node-gyp rebuild`
633 error Exit status 1
634 error Failed at the @felixrieseberg/spellchecker@4.0.10 install script.
634 error This is probably not a problem with npm. There is likely additional logging output above.
635 verbose exit [ 1, true ]
```

I've been digging around in some other GitHub issues that seem sorta similar:

https://github.com/nodejs/node-gyp/issues/65
https://github.com/nodejs/node-gyp/issues/1701

But, those are issues with special characters / spaces. It's very possible that I'm barking up the wrong tree, but I thought I'd start here. I'm very new to electron, so any help you have would be much appreciated.

🙏🙏🙏

**Comment by JorisWillekens** [comment]
I'm having the same issue

**Comment by garrettm** [comment]
I'm having the same issue with:
yarn v1.10.1
electron v5.0.3 and v6.0.0
node v12.7.0

**Comment by eliduke** [comment]
I was able to fix this by upgrading node. My current setup is as follows now:
```
Node v10.16.0
NPM v6.9.0
Electron v1.8.8
```

**Comment by SRINIVAS-B-SINDAGI** [comment]
fix for the above issue?
is it a version issue?
