### ISSUE TITLE
Warning: Missing input files: node_modules\@felixrieseberg\spellchecker\build\..\vendor\hunspell\src\build\build.h

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-spellchecker#166]
node: 13.2.0
node-gyp: 5.0.5
npm: 6.13.1
Electron: 7.1.3
electron-spellchecker: 2.2.1
On npm install I get this:

Warning: Missing input files:
D:\Projects\Electron\node_modules\@felixrieseberg\spellchecker\build\..\vendor\hunspell\src\build\build.h
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:464:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\Electron\node_modules\@felixrieseberg\spellchecker
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! @felixrieseberg/spellchecker@4.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the @felixrieseberg/spellchecker@4.0.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any suggestions?

**Comment by etyp** [comment]
We're experiencing the same issue when attempting to do our Windows build. We've tried updating `windows-build-tools` and `node-gyp` with no success.

We're a bit stuck on doing a new release until we can resolve. Let me know if there's any more information I can provide to help debug.
