### ISSUE TITLE
Missing lru-cache dependency in latest

### ISSUE THREAD

**Issue by ccnokes** [electron-userland/electron-spellchecker#20]
Looks like it just wasn't added to the package.json after this change https://github.com/paulcbetts/electron-spellchecker/commit/eafd251ec890558c614d9b888cd513033ce2e63c. I was going to PR it but then the project's install/build wasn't working. 

If you happen to know why it's not working, I'd like to know..... here's the output:

```
cameronnokes$ npm install

> electron-spellchecker@0.5.10 prepublish /Users/cameronnokes/Repos/electron-spellchecker
> npm run compile


> electron-spellchecker@0.5.10 compile /Users/cameronnokes/Repos/electron-spellchecker
> babel -d lib/ src/

module.js:457
    throw err;
    ^

Error: Cannot find module './lib/api/node.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cameronnokes/Repos/electron-spellchecker/node_modules/babel-core/index.js:1:80)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by paulcbetts** [comment]
Fixed!
