### ISSUE TITLE
install fails at node-gyp rebuild [windows and Linux]

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-spellchecker#39]
0.6.2 version worked well on all the platforms. I just updated to v1.0.0 which fails at `node-gyp rebuild` on windows and Linux. It's probably because of the latest version of keyboard layout module.

Platform - Ubuntu 14.04
node - v6..9.4
Logs - [linux](http://pastebin.com/FPXnpBnD)
```sh
➜  electron-spellchecker git:(master) npm install

> keyboard-layout@2.0.10 install /home/akash/dev/electron-spellchecker/node_modules/keyboard-layout
> node-gyp rebuild

make: Entering directory '/home/akash/dev/electron-spellchecker/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
In file included from ../src/keyboard-layout-manager-linux.cc:1:0:
../src/keyboard-layout-manager.h:7:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
keyboard-layout-manager.target.mk:96: recipe for target 'Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o' failed
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
make: Leaving directory '/home/akash/dev/electron-spellchecker/node_modules/keyboard-layout/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/akash/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/home/akash/.nvm/versions/node/v6.9.4/bin/node" "/home/akash/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/akash/dev/electron-spellchecker/node_modules/keyboard-layout
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/akash/.nvm/versions/node/v6.9.4/bin/node" "/home/akash/.nvm/versions/node/v6.9.4/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@2.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keyboard-layout@2.0.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keyboard-layout
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/akash/dev/electron-spellchecker/npm-debug.log

```

**Comment by paulcbetts** [comment]
You need a dev package for X11 to get this work

**Comment by akashnimare** [comment]
> You need a dev package for X11 to get this work
Sorry, but I didn't get this. Do I need to install something?

**Comment by paulcbetts** [comment]
```sh
apt-get install libxext-dev libXtst-dev libxkbfile-dev
```

**Comment by akashnimare** [comment]
Thanks a lot, it worked on Linux although it still exists on windows machine. Do you know what I need to install on windows to make it work? I'm on windows 7. Thanks again for all the help.

**Comment by patilrevansidh** [comment]
@anaisbetts how about windows. `sudo apt-get install libxext-dev libxtst-dev libxkbfile-dev` worked on Ubuntu

**Comment by patilrevansidh** [comment]
> ```shell
> sudo apt-get install libxext-dev libXtst-dev libxkbfile-dev
> ```

@anaisbetts how about windows. sudo apt-get install libxext-dev libxtst-dev libxkbfile-dev worked on Ubuntu
