### ISSUE TITLE
Error when trying to use

### ISSUE THREAD

**Issue by Slapbox** [electron-userland/electron-spellchecker#52]
```
Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Projects\myApp\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\myApp\app\node_modules\keyboard-layout\lib\keyboard-layout.js:4:31)
    at Object.<anonymous> (C:\Projects\myApp\app\node_modules\keyboard-layout\lib\keyboard-layout.js:59:3)
```

Most other references I can find to a bug like this on the web are either due to running an x86 package on x64, or there is no known cause.

Any thoughts on this one? Thanks very much for your great work and your time.

**Comment by Slapbox** [comment]
Stacktrace:

```
module.(anonymous function) (ELECTRON_ASAR.js:173)
Module._extensions..node (module.js:598)
module.(anonymous function) (ELECTRON_ASAR.js:173)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
(anonymous) (C:\Projects\app…rd-layout.js:4)
(anonymous) (C:\Projects\app…d-layout.js:59)
Module._compile (module.js:571)
Module._extensions..js (module.js:580)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
(anonymous) (C:\Projects\app…k-handler.js:7)
(anonymous) (C:\Projects\app…handler.js:705)
Module._compile (module.js:571)
Module._extensions..js (module.js:580)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
(anonymous) (C:\Projects\app…ib\index.js:15)
(anonymous) (C:\Projects\app…ib\index.js:41)
Module._compile (module.js:571)
Module._extensions..js (module.js:580)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
17 (external "elect…pellchecker":1)
__webpack_require__ (bootstrap 9c8d0…0c0ed44c20:659)
fn (bootstrap 9c8d0…40c0ed44c20:83)
./app/index.js (index.js:9)
__webpack_require__ (bootstrap 9c8d0…0c0ed44c20:659)
fn (bootstrap 9c8d0…40c0ed44c20:83)
22 (bundle.js:277011)
__webpack_require__ (bootstrap 9c8d0…0c0ed44c20:659)
module.exports../app/actions/notes_actions.js.Object.defineProperty.value (bootstrap 9c8d0…0c0ed44c20:708)
(anonymous) (bootstrap 9c8d0…0c0ed44c20:708)
```

**Comment by Slapbox** [comment]
Resolved here: https://github.com/chentsulin/electron-react-boilerplate/issues/815
